name: AutoAssignReviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign-reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
      with:
        config: '.github/auto_assign.yml'
        token: ${{ secrets.MYGITHUB_TOKEN }}
