name: "Auto Assign"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

  assign-reviewers1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true        

  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v.1.0.1
      with:
        repo-token: ${{ secrets.MYGITHUB_TOKEN }}
        teams: "gitub-org-team"         # only works for GitHub Organisation/Teams
        persons: "rowi1de"              # add individual persons here 
        include-draft: false            # Draft PRs will be skipped (default: false)
        skip-with-manual-reviewers: 0 
